<a href="https://colab.research.google.com/github/soheldatta17/Vector_Operations/blob/main/vector_operations_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy Library

In [112]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [113]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [114]:
print(A)

[[2 3]
 [4 5]]


In [115]:
print(B)

[[6 7]
 [8 9]]


In [116]:
A.shape

(2, 2)

In [117]:
B.shape

(2, 2)

Adding two Matrices

In [118]:
sum = A + B

In [119]:
print(sum)

[[ 8 10]
 [12 14]]


In [120]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [121]:
print(matrix_1)

[[2 5 3]
 [6 2 0]
 [9 0 0]]


In [122]:
print(matrix_2)

[[ 5  3  3]
 [19  0 10]
 [ 7  3  2]]


In [123]:
sum = np.add(matrix_1, matrix_2)

In [124]:
print(sum)

[[ 7  8  6]
 [25  2 10]
 [16  3  2]]


In [125]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

**Matrix Subtraction**

In [126]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [127]:
print(A)

[[2 3]
 [4 5]]


In [128]:
print(B)

[[6 7]
 [8 9]]


In [129]:
difference = A - B

In [130]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [131]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [132]:
print(matrix_1)

[[7 0 3]
 [3 1 8]
 [4 0 6]]


In [133]:
print(matrix_2)

[[ 8 13 19]
 [18  2  0]
 [ 6  3 13]]


In [134]:
diff = np.subtract(matrix_1, matrix_2)

In [135]:
print(diff)

[[ -1 -13 -16]
 [-15  -1   8]
 [ -2  -3  -7]]


**Multiplying a matrix by a scalar**

In [136]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[7 2 0 8]
 [7 0 1 7]
 [3 3 4 7]
 [6 2 8 5]]


In [137]:
product = np.multiply(x,y)

In [138]:
print(product)

[[35 10  0 40]
 [35  0  5 35]
 [15 15 20 35]
 [30 10 40 25]]


**Multiplying 2 Matrices**

In [139]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [140]:
print(matrix_3)

[[0 4 1]
 [4 1 4]
 [3 0 3]]


In [141]:
print(matrix_4)

[[0 4 1 2]
 [2 1 0 3]
 [2 3 3 0]]


In [142]:
product = np.dot(matrix_3, matrix_4)

In [143]:
print(product)

[[10  7  3 12]
 [10 29 16 11]
 [ 6 21 12  6]]


In [144]:
product.shape

(3, 4)

In [145]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [146]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [147]:
print(matrix_3)

[[2 3 1]
 [3 1 0]
 [4 1 0]]


In [148]:
print(matrix_4)

[[1 0 4]
 [1 0 4]
 [0 3 2]]


In [149]:
product = np.multiply(matrix_3, matrix_4)

In [150]:
print(product)

[[2 0 4]
 [3 0 0]
 [0 3 0]]


In [151]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))